name: Lightweight Branch CI

on:
    push:
        branches:
            - "**"

jobs:
    validate-backend:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-dotnet@v4
              with:
                  dotnet-version: "9.0.x"

            # Fails if the code doesn't compile
            - name: Build Backend
              working-directory: ./backend/coordina
              run: dotnet build

            # Optional: Fails if the C# code is poorly formatted
            - name: Check Formatting
              working-directory: ./backend/coordina
              run: dotnet format --verify-no-changes

    validate-frontend-and-tests:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                  node-version: "20"

            - name: Install Dependencies
              working-directory: ./test
              run: npm ci

            # Fails if ESLint finds errors
            - name: Run Linter
              working-directory: ./test
              run: npm run lint --if-present
